# Generated by Django 5.1.1 on 2025-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educoredb_app', '0002_onlineclassroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
